controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ["middle_left_wheel_joint"]
    right_wheel_names: ["middle_right_wheel_joint"]
    wheel_separation: 0.336
    wheel_radius: 0.034
    use_stamped_vel: false
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.8
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 2.0
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 2.0